In [26]:
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy import text

import pandas as pd
from faker import Faker
from random import randint, choice
from datetime import datetime

### Připojení na DB

In [3]:
# base for table classes -> ORM connection between classes and tables
Base = declarative_base()

# connection to DB
engine = create_engine('mysql+pymysql://rektorat:rektorat12345@localhost/projekt_vs')

# link for writing data -> adding and commiting
Session = sessionmaker(bind=engine)
link = Session()

C:\Users\cejs0\AppData\Local\Temp\ipykernel_14960\560522198.py:2: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

### Generování náhodných dat

In [ ]:
# generátor studentů
fake = Faker('cs_CZ')
studenti = []

pocet_studentu = 100

for i in range(pocet_studentu):
    # vygeneruj náhodného člověka a jeho zdravotní a platební údaje
    student = {"jmeno": fake.first_name(), "prijmeni": fake.last_name(), "vek": randint(19, 26)}
    studenti.append(student)

studenti_df = pd.DataFrame.from_records(studenti)
studenti_df

        jmeno   prijmeni  vek
0       Adéla     Blažek   23
1     Vendula     Sýkora   23
2    Jaroslav  Valentová   23
3       Libor   Havlíček   23
4    Bohuslav    Novotná   26
..        ...        ...  ...
95    Hedvika       Kříž   21
96      Josef    Novotný   20
97        Oto   Stejskal   21
98  Dobroslav     Dvořák   22
99      Artur   Kučerová   24

[100 rows x 3 columns]

In [5]:
# generátor učitelů
fake = Faker('cs_CZ')
ucitele = []

pocet_ucitelu = 10

for i in range(pocet_ucitelu):
    # vygeneruj náhodného člověka a jeho zdravotní a platební údaje
    ucitel = {"jmeno": fake.first_name(), "prijmeni": fake.last_name(), "vek": randint(27, 67)}
    ucitele.append(ucitel)

ucitele_df = pd.DataFrame.from_records(ucitele)
ucitele_df

       jmeno    prijmeni  vek
0     Martin       Bárta   55
1    Bedřich    Nováková   31
2      Josef   Strnadová   36
3     Dorota     Šmídová   64
4     Růžena     Novotný   63
5     Mojmír    Kučerová   57
6      Vilém    Pospíšil   61
7       Zora    Havlíček   51
8  Dobroslav       Hájek   46
9      Ivana  Horváthová   27

In [ ]:
# generátor učeben
fake = Faker('cs_CZ')
ucebny = []

pocet_uceben = 4

for i in range(pocet_uceben):
    # vygeneruj náhodného člověka a jeho zdravotní a platební údaje
    ucebna = {"jmeno": fake.first_name_female(), "stat": fake.state(), "mesto": fake.city_name(), "adresa": fake.street_address()}
    ucebny.append(ucebna)

ucebny_df = pd.DataFrame.from_records(ucebny)
ucebny_df

       jmeno                  stat     mesto                adresa
0  Miroslava          Ústecký kraj  Frýdlant        U Hřbitova 606
1      Nikol       Pardubický kraj  Neveklov  U Dětského Hřiště 63
2     Johana  Královéhradecký kraj      Luby        Tichonická 858
3     Renata        Olomoucký kraj  Lovosice          U Dobešky 57

In [20]:
# generátor předmětů
fake = Faker('cs_CZ')
predmety = [{"jmeno": "Chemie"}, {"jmeno": "Matematika"}, {"jmeno": "Data Science"}]

predmety_df = pd.DataFrame.from_records(predmety)
predmety_df

          jmeno
0        Chemie
1    Matematika
2  Data Science

In [29]:
choice(ucebny_df.index + 1)

4

In [ ]:
studenti_df.index

RangeIndex(start=1, stop=101, step=1)

In [30]:
# generátor zkoušek

datum = datetime.utcnow().isoformat()

zkousky = []
pocet_zkousek = 10

for i in range(pocet_zkousek):
    # vygeneruj náhodného člověka a jeho zdravotní a platební údaje
    zkouska = {"datum": datum, "Ucebna_id": choice(ucebny_df.index + 1), "Student_id": choice(studenti_df.index + 1), "Ucitel_id": choice(ucitele_df.index + 1), "Predmet_id": choice(predmety_df.index + 1)}
    zkousky.append(zkouska)

zkousky_df = pd.DataFrame.from_records(zkousky)
zkousky_df

                        datum  Ucebna_id  Student_id  Ucitel_id  Predmet_id
0  2024-11-27T18:51:18.263686          2          89          2           1
1  2024-11-27T18:51:18.263686          3          94          5           2
2  2024-11-27T18:51:18.263686          2          17          5           3
3  2024-11-27T18:51:18.263686          4          55         10           3
4  2024-11-27T18:51:18.263686          2          58          5           3
5  2024-11-27T18:51:18.263686          4          24          6           1
6  2024-11-27T18:51:18.263686          3          64          7           1
7  2024-11-27T18:51:18.263686          4          61          2           3
8  2024-11-27T18:51:18.263686          4          23          5           1
9  2024-11-27T18:51:18.263686          3          55          6           1

In [33]:
# generátor výsledků

vysledky = []

for i in zkousky:
    body = randint(20, 100)
    prosel = 1 if body > 50 else 0
    # vygeneruj náhodného člověka a jeho zdravotní a platební údaje
    vysledek = {"Zkouska_id": choice(zkousky_df.index + 1), "Prosel": prosel, "Pocet_bodu": body}
    vysledky.append(vysledek)

vysledky_df = pd.DataFrame.from_records(vysledky)
vysledky_df

   Zkouska_id  Prosel  Pocet_bodu
0           4       0          32
1           4       1          96
2          10       1          66
3           6       1          60
4           4       0          45
5           9       0          47
6           4       0          49
7           2       0          48
8          10       1          51
9          10       0          32

### Uložení dat do databáze

In [39]:
# využijeme .to_sql metodu z pandas -> zápis do sql pomocí pandas
studenti_df.to_sql(name='student', con=engine, if_exists='replace')
ucitele_df.to_sql(name='ucitel', con=engine, if_exists='replace')
predmety_df.to_sql(name='predmet', con=engine, if_exists='replace')
ucebny_df.to_sql(name='ucebna', con=engine, if_exists='replace')

OperationalError: (pymysql.err.OperationalError) (3730, "Cannot drop table 'student' referenced by a foreign key constraint 'fk_Zkouska_Student1' on table 'zkouska'.")
[SQL:
DROP TABLE student]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:
zkousky_df.to_sql(name='zkouska', con=engine, if_exists='replace')
vysledky_df.to_sql(name='vysledek', con=engine, if_exists='replace')

OperationalError: (pymysql.err.OperationalError) (3730, "Cannot drop table 'zkouska' referenced by a foreign key constraint 'fk_Vysledek_Zkouska1' on table 'vysledek'.")
[SQL:
DROP TABLE zkouska]
(Background on this error at: https://sqlalche.me/e/20/e3q8)